import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ProviderComp } from "@/components/practice/provider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

import { Providers } from "./firebase/provider/NextUI";

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Providers>
          <ProviderComp>{children}</ProviderComp>
        </Providers>
      </body>
    </html>
  );
}
